#!/bin/sh
baseA3=#002b36
baseA2=#073642
baseA0=#657b83
orange=#cb4b16
exec dmenu  -b -h 18  -i -nb $baseA3 -nf $baseA0 -sb $baseA2 -sf $orange "$@" -fn -Misc-Fixed-Medium-R-Normal--18-120-100-100-C-90-ISO10646-1 -h 29
