#!/bin/sh
baseA3=#002b36
baseA2=#073642
baseA0=#657b83
orange=#cb4b16
exec dmenu  -b -h 25  -i -nb $baseA3 -nf $baseA0 -sb $baseA2 -sf $orange "$@" -fn -misc-fixed--medium-r-normal--13-120-75-75-C-70-iso10646-1
